version: "3.8"

services:
  dolphin-api:
    image: 9164820596/dolphin-backend:latest
    ports:
      - "5000:5000"
    environment:
      MongoDbSettings__Host: mongodb
      MongoDbSettings__Port: "27017"
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: 9164820596/dolphinwebapp:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - dolphin-api
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    volumes:
      - ./mongo-data:/dolphin/db
    ports:
      - "27017:27017"
    restart: always
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
